### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by Shukurullo-Faxriddinovich** [Muhammadkul-Khurboyev/LasLestVPN#1]
![Screenshot_1](https://github.com/Muhammadkul-Khurboyev/LasLestVPN/assets/96634850/00c6f565-2fa0-495d-849a-2ce89f5049fe)
![Screenshot_2](https://github.com/Muhammadkul-Khurboyev/LasLestVPN/assets/96634850/cfc12f7e-9e36-4bc6-94f9-355992b0c85c)
bu holatda sayt logotipi height bo'yicha muommo borligi ko'rsatilgan shun holatni to'g'irlab qo'ysak yaxshi bo'lar edi

**Comment by Muhammadkul-Khurboyev** [comment]
Assalomu alekum aha Shukurullo aka sizni tushundim togrlab qoyaman
