### ISSUE TITLE
issue2

### ISSUE THREAD

**Issue by Shukurullo-Faxriddinovich** [Muhammadkul-Khurboyev/LasLestVPN#2]
![Screenshot_3](https://github.com/Muhammadkul-Khurboyev/LasLestVPN/assets/96634850/0acc7115-528c-4b1f-9903-0a032eac5a5c)
bu joyda brend logotiplari alohida alohida anchorda linklari ko'rsatilgan holatda bo'lishi kerak edi

**Comment by Muhammadkul-Khurboyev** [comment]
Aha tushunarli 👍👍👍👍👍
